version: '3'
services:

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:8.4.5
    user: "${UID}:${GID}"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - EMONESP_IP=${EMONESP_IP}
      - EMONESP_USER=${EMONESP_USER}
      - EMONESP_PASS=${EMONESP_PASS}
      - TZ=${TZ}
    ports:
      - 3000:3000
    networks:
      - emonesp_mon_network
    restart: unless-stopped
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y' # How long historical data should be saved
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    user: "${UID}:${GID}"
    environment:
      - TZ=${TZ}
    ports:
      - 9090:9090
    networks:
      - emonesp_mon_network
    restart: unless-stopped
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/config:/etc/prometheus

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    user: "${UID}:${GID}"
    environment:
      - TZ=${TZ}
    ports:
      - 1883:1883
    networks:
      - emonesp_mon_network
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto

  mqtt2prometheus:
    container_name: mqtt2prometheus
    hostname: mqtt2prometheus
    image: ghcr.io/hikhvar/mqtt2prometheus:latest
    user: "${UID}:${GID}"
    environment:
      - TZ=${TZ}
    networks:
      - emonesp_mon_network
    restart: unless-stopped
    volumes:
      - ./mqtt2prometheus/prometheus2mqtt_config.yaml:/config.yaml

networks:
  emonesp_mon_network:
