{
 "title": "Energy monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Latest Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.W", "name": "", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "",
       ""
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.totV", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current CT1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.CT1", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.freq", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.PF", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "emonESP Satus",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.[*~]", "name": "Keys" },
      { "jsonPath": "$.[*]", "language": "jsonpath", "name": "Values" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Latest Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.[*~]", "name": "Keys" },
      { "jsonPath": "$.[*]", "language": "jsonpath", "name": "Values" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current CT2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.CT2", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.temp", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  { "title": "Historical Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "W{instance=\"mqtt2prometheus:9641\"}",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "MAX-AVG-MIN",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 2, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "W{sensor=\"W\"}",
     "legendFormat": "P"
    }
   ]
  },
  {
   "title": "Energy consumption (1h avg)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$P_1h_AVG/1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "totV{sensor=\"totV\"}",
     "legendFormat": "Voltage"
    },
    {
     "expr": "freq{sensor=\"freq\"}",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "CT1{sensor=\"CT1\"}",
     "legendFormat": "CT1"
    },
    {
     "expr": "CT2{sensor=\"CT2\"}",
     "legendFormat": "CT2"
    },
    {
     "expr": "totI{sensor=\"totI\"}",
     "legendFormat": "Total current"
    }
   ]
  },
  {
   "title": "Total energy consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "C", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Cost for period of time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($D/1000)*0.24028", "type": "math" }
   ]
  }
 ]
}